### ISSUE TITLE
你这个程序的服务器端和客户端之间的连接没有加密吧？

### ISSUE THREAD

**Issue by luckypoem** [DavidAlphaFox/socks5#1]
hi 。

我看了2边的参数，没看见加密的参数。

**Comment by DavidAlphaFox** [comment]
> 

  {ok,Enc} = proxy_chiper:encrypt(Payload, Chiper)
参考这个

**Comment by luckypoem** [comment]
hi.

root@racknerd-7b97d8:~/socks5-by-DavidAlphaFox# make
 DEP    ranch (1.7.1)
 DEP    ailib (v0.4.4)
 DEP    aiconf (v0.1.7)
 DEP    aiutp ()
The authenticity of host 'github.com (192.30.255.112)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.255.112' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: 无法读取远程仓库。

请确认您有正确的访问权限并且仓库存在。
/bin/sh: 1: cd: can't cd to /root/socks5-by-DavidAlphaFox/deps/aiutp
erlang.mk:5087: recipe for target '/root/socks5-by-DavidAlphaFox/deps/aiutp' failed
make: *** [/root/socks5-by-DavidAlphaFox/deps/aiutp] Error 2
root@racknerd-7b97d8:~/socks5-by-DavidAlphaFox#

怎么make遇错了？

**Comment by DavidAlphaFox** [comment]
fixed

**Comment by luckypoem** [comment]
hi.

这次make成功，不过具体如何运行服务器端命令和客户端命令？
能把完整的命令写出来吗？

root@racknerd-7b97d8:~/socks5-by-DavidAlphaFox/_rel/proxy/bin# ls
install_upgrade.escript  no_dot_erlang.boot  proxy-0.1.3
nodetool                 proxy               start_clean.boot
root@racknerd-7b97d8:~/socks5-by-DavidAlphaFox/_rel/proxy/bin# ./proxy -h
Usage: proxy {start|start_boot <file>|foreground|stop|restart|reboot|pid|ping|console|console_clean|console_boot <file>|attach|remote_console|upgrade|downgrade|install|uninstall|versions|escript|rpc|rpcterms|eval|status|undefined}
root@racknerd-7b97d8:~/socks5-by-DavidAlphaFox/_rel/proxy/bin# ./proxy-0.1.3 -h
Usage: proxy {start|start_boot <file>|foreground|stop|restart|reboot|pid|ping|console|console_clean|console_boot <file>|attach|remote_console|upgrade|downgrade|install|uninstall|versions|escript|rpc|rpcterms|eval|status|undefined}
root@racknerd-7b97d8:~/socks5-by-DavidAlphaFox/_rel/proxy/bin#

**Comment by DavidAlphaFox** [comment]
服务端，将default.json.server复制为default.json放到_rel下面的etc目录中，
客户端，将default.json.client复制为default.json放到_rel下面的etc目录中，修改"server_host": ["192.168.0.1"]为真正的服务器地址。
服务端和客户端都使用proxy start运行

**Comment by luckypoem** [comment]
hi.

在我的Mac上，make还是遇错。
yudeMacBook-Air:socks5-by-DavidAlphaFox ym$ make
erlang.mk:26: Please upgrade to GNU Make 4 or later: https://erlang.mk/guide/installation.html
 DEP    ranch (1.7.1)
 DEP    ailib (v0.4.4)
 DEP    aiconf (v0.1.7)
 DEP    aiutp ()

error: RPC failed; result=18, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
/bin/sh: line 0: cd: /Users/ym/socks5-by-DavidAlphaFox/.erlang.mk/rebar: No such file or directory
fatal: reference is not a tree: 576e12171ab8d69b048b827b92aa65d067deea01
/bin/sh: ./bootstrap: No such file or directory
/bin/sh: line 0: cd: OLDPWD not set
{"init terminating in do_boot",{undef,[{rmemo,start,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,657}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,121}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
 DEPEND ranch.d
 ERLC   ranch.erl ranch_acceptor.erl ranch_acceptors_sup.erl ranch_app.erl ranch_conns_sup.erl ranch_crc32c.erl ranch_listener_sup.erl ranch_protocol.erl ranch_proxy_header.erl ranch_server.erl ranch_ssl.erl ranch_sup.erl ranch_tcp.erl ranch_transport.erl
src/ranch.erl:130: illegal use of variable 'Key' in map
make[2]: *** [ebin/ranch.app] Error 1
make[1]: *** [app] Error 2
make: *** [deps] Error 2
yudeMacBook-Air:socks5-by-DavidAlphaFox ym$ 
（这里我挂了vpn)
yudeMacBook-Air:socks5-by-DavidAlphaFox ym$ make
erlang.mk:26: Please upgrade to GNU Make 4 or later: https://erlang.mk/guide/installation.html
 ERLC   ranch.erl ranch_acceptor.erl ranch_acceptors_sup.erl ranch_app.erl ranch_conns_sup.erl ranch_crc32c.erl ranch_listener_sup.erl ranch_protocol.erl ranch_proxy_header.erl ranch_server.erl ranch_ssl.erl ranch_sup.erl ranch_tcp.erl ranch_transport.erl
src/ranch.erl:130: illegal use of variable 'Key' in map
make[2]: *** [ebin/ranch.app] Error 1
make[1]: *** [app] Error 2
make: *** [deps] Error 2
yudeMacBook-Air:socks5-by-DavidAlphaFox ym$

挂了vpn后，make还是遇错。不知怎么解决？

**Comment by DavidAlphaFox** [comment]
已经修正了Makefile中的依赖，需要先删除deps/aiutp后重新获取依赖。
在Mac OS X上无法使用Erlang/OTP 25进行编译，需要使用Erlang/OTP 23或24进行编译。
由于国内访问github会出现闪断情况，因此有时依赖仓库无法正确的clone，需要手动删除相关依赖再次进行获取。

**Comment by luckypoem** [comment]
hi.

mac上面，安装比较麻烦。可否提供mac上面的绿色软件包下载？

**Comment by DavidAlphaFox** [comment]
> 

很抱歉，目前没有相关计划。并且类似工具github上有很多。可以使用其它工具来代替这个工具。
